
# 配置文件加密key
jasypt:
  encryptor:
    password: xboot
pdd:
  preOrderUrl: https://mobile.yangkeduo.com/proxy/api/order
  aliPayUrl: https://mobile.yangkeduo.com/proxy/api/order/prepay
  returnUrl: https://mobile.yangkeduo.com/transac_wappay_callback.html
  clientId: 41dc767f963d412fa2b944ed21c4ac7d
  clientSecret: 85d6e8f71f3014bbd91dbe99171d0cb6b5082322
  code: ba9eda7c693c4989b16af37a0fd1904801f8b598
  accessToken: 6b675a12c1b641a0b099e70f9cf5b227f724d780
  confirmUrl: http://mobile.yangkeduo.com/proxy/api/order/
  sentUrl: https://mms.pinduoduo.com/robot/shop/orders/shipping
  orderListUrl: https://mms.pinduoduo.com/mars/shop/orderList
  cookie: api_uid=rBQRx1yz47mcSTK/hlv9Ag==; _ga=GA1.2.1766181771.1557195658; _nano_fp=XpdynqXolpEynqXbXC_4UEMP~eTwcBe01S1Z~_Gc; pt_691035c2=uid=tdc1zC0-4i5h/o5kOtte6Q&nid=0&vid=uWvcpatpLuNDsu0ZQ6g2Gw&vn=2&pvn=1&sact=1557889437383&to_flag=0&pl=HJPHbMMwQ-lnEQahY4iRFA*pt*1557889437383; accesstoken=9183389ca483885eca701be625e088ea4ea59500e8f64; PASS_ID=1-XU1WnLjc7Cs7OuNix3WYa5XRqo5F/Ghg96dZzzpMhA/fEUQqOBFvXZ+QJXwgBLk9ylwlw2n0l8SmhhdlhLvIXQ_581782377_34449056
yz:
  preOrderUrl: https://cashier.youzan.com/pay/wsctrade/order/buy/v2/bill.json
  payUrl: https://cashier.youzan.com/wsctrade/pay/wsc/pay.json
  confirmUrl: https://h5.youzan.com/wsctrade/order/confirmReceive.json
  sentUrl: https://www.youzan.com/v2/trade/newOrderDelivery/delivery.json
  orderListUrl: https://www.youzan.com/v4/trade/order/getList.json?buy_way=all&express_type=all&feedback=all&is_star=all&order_label=order_no&order_source=all&p=1&state=send&type=all
  goodsListUrl: https://www.youzan.com/v4/goods/goods/list.json?p=1&pageSize=20&keyword=&orderby=created_time&order=desc
  goodsDetailUrl: https://www.youzan.com/v2/showcase/goods/mallItem.json
  getItemIdUrl: https://www.youzan.com/v2/trade/newOrderDelivery/deliveryWindow.json
  userAddressUrl: https://h5.youzan.com/wsctrade/order/address/list?switchable=false
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  #rabbitmq
  rabbitmq:
    host: 172.23.60.8
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
  # 数据源
  datasource:
    url: jdbc:mysql://81.70.63.250:3306/pay-all?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: payall
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    #password: ENC(F4B0s6u9xcDw3V+P0qC4CA==)
    password: fuckiot123!
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    # Druid StatViewServlet配置
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
  # Redis
  redis:
    host: 172.23.60.8
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 3000
  # Elasticsearch
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  # 定时任务
  quartz:
    # 任务信息存储至数据库
    job-store-type: jdbc

tax:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  # ES
  elasticsearch:
    nodeClient: 127.0.0.1:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: false
  # 七牛云配置
  qiniu:
    accessKey: 你的accessKey
    secretKey: 你的secretKey
    bucket: 你的空间名
    domain: 你的测试域名，如http://p77xsahe9.bkt.clouddn.com
    # 存储区域 -1自动判断 0华东 1华北 2华南 3北美 4东南亚
    zone: -1
  # mob api配置 mob官网注册申请即可
  mob:
    appKey: 你的appKey

# 忽略鉴权url
ignored:
  urls:
    - /xboot/user/regist
    - /xboot/common/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**
    - /**


# Swagger界面内容配置
swagger:
  title: XBoot API接口文档
  description: XBoot Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: Exrick
    url: http://blog.exrick.cn
    email: 1012139570@qq.com

#MyBatis配置
mybatis:
  type-aliases-package: com.chaotu.tax.po
  mapper-locations: classpath:mapper/*.xml
mapper:
  identity: MYSQL
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=conutSql
  helper-dialect: mysql

# 日志
logging:
  file: xboot-logs/xboot.log
  # 显示sql语句
  level:
    com:
      chaotu:
        pay:
          dao: debug



